spring:
  application:
    name: chat-conversacion

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chat_conversacion}

server:
  port: 8082
  error:
    include-message: never
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    com.arquetipo.demo: DEBUG
